import flet as ft


def button_page_(page_):
    return ft.ResponsiveRow(
        [
            ft.Container(
                width=450,
                height=700,
                padding=40,
                content=ft.Column(
                    horizontal_alignment="center",
                    alignment="center",
                    controls=[
                        ft.Row(
                            [
                                ft.ElevatedButton(
                                    "Button1",
                                    width=150,
                                    height=150,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=10),
                                    ),
                                ),
                                ft.ElevatedButton(
                                    "Button2",
                                    width=150,
                                    height=150,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=10),
                                    ),
                                ),
                            ],
                            alignment=ft.MainAxisAlignment.CENTER,
                        ),
                        ft.Row(
                            [
                                ft.ElevatedButton(
                                    "Button3",
                                    width=150,
                                    height=150,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=10),
                                    ),
                                ),
                                ft.ElevatedButton(
                                    "Button4",
                                    width=150,
                                    height=150,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=10),
                                    ),
                                ),
                            ],
                            alignment=ft.MainAxisAlignment.CENTER,
                        ),
                    ],
                ),
            )
        ]
    )
